---
- name: Demonstration of ansible-bender's functionality
  hosts: all
  vars:
    ansible_bender:
      base_image: fedora:30
      working_container:
        volumes:
          - '{{ playbook_dir }}:/src:Z'
      target_image:
        name: ansiblefest-image
        working_dir: /src
        labels:
          built-by: '{{ ansible_user }}'
  tasks:
  - name: Run a sample command
    command: 'ls -lha /src'
  - name: Copy index.html to /etc
    copy:
      src: index.html
      dest: /etc/
